remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Julian Lawrence
description: Projects, Problems, and Blog Posts About My Programming Journey

defaults:
  -
    scope:
      path: "about"
      type: "pages"
    values:
      layout: "default"
      permalink: /:path/:basename
  -
    scope:
      path: "blog"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "blog" # overrides previous default layout
      author: "Julian"
      permalink: /:path/:basename
-
    scope:
      path: ""
      type: "post" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout
      author: "Julian"
      permalink: /:categories/:year/:month/:title
