remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Julian Lawrence
description: Projects, Problems, and Blog Posts About My Programming Journey
defaults:
  -
    scope:
      path: "blog"
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
