remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Julian Lawrence
description: Projects, Problems, and Blog Posts About My Programming Journey

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "blog"
      permalink: /:path/:basename

  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /:categories/:year/:month/:day/:title/
